include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - camel_case_types

analyzer:
#   exclude:
#     - path/to/excluded/files/**
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false